import os

with open("E:/CAD自动化制图/interior_cad.html","r",encoding="utf-8") as f:
    html = f.read()
c = 0

# ==================== 1. TRIM/EXTEND COMMANDS ====================
trim_code = """
// ===================== 修剪/延伸 =====================
var trimMode = false; // "trim" or "extend"
var cutEdge = null;

window.activateTrim = function(){
  if(!sel){
    document.getElementById("tool-status").textContent="  修剪: 先选中要作为剪切边的墙";
    return;
  }
  cutEdge = sel;
  trimMode = "trim";
  document.getElementById("tool-status").textContent="  修剪: 点击要修剪的墙段 (点击端点侧保留)";
};

window.activateExtend = function(){
  if(!sel){
    document.getElementById("tool-status").textContent="  延伸: 先选中作为边界的墙";
    return;
  }
  cutEdge = sel;
  trimMode = "extend";
  document.getElementById("tool-status").textContent="  延伸: 点击要延伸的墙";
};

// Handle trim/extend clicks
function doTrimOrExtend(wp){
  if(trimMode==="trim" || trimMode==="extend"){
    // Find closest wall to click point
    var closest = null, minDist = Infinity;
    for(var i=0;i<walls.length;i++){
      if(walls[i]===cutEdge)continue;
      var d = distToSegment(wp.x,wp.y,walls[i].x1,walls[i].y1,walls[i].x2,walls[i].y2);
      if(d < minDist){minDist=d;closest=i;}
    }
    if(closest===null || minDist > 200){return false;}
    
    saveState();
    var w = walls[closest];
    
    if(trimMode==="trim"){
      // Find intersection with cut edge
      var inter = lineIntersection(w.x1,w.y1,w.x2,w.y2, cutEdge.x1,cutEdge.y1,cutEdge.x2,cutEdge.y2);
      if(inter){
        // Determine which side of the intersection the click is on
        var d1 = Math.hypot(wp.x-w.x1,wp.y-w.y1);
        var d2 = Math.hypot(wp.x-w.x2,wp.y-w.y2);
        if(d1 < d2){ w.x1 = inter.x; w.y1 = inter.y; }
        else { w.x2 = inter.x; w.y2 = inter.y; }
        document.getElementById("tool-status").textContent="  修剪完成";
      }
    } else {
      // Extend: extend wall to meet cut edge
      var inter = lineIntersection(w.x1,w.y1,w.x2,w.y2, cutEdge.x1,cutEdge.y1,cutEdge.x2,cutEdge.y2);
      if(inter){
        var d1 = Math.hypot(wp.x-w.x1,wp.y-w.y1);
        var d2 = Math.hypot(wp.x-w.x2,wp.y-w.y2);
        if(d1 < d2){ w.x1 = inter.x; w.y1 = inter.y; }
        else { w.x2 = inter.x; w.y2 = inter.y; }
        document.getElementById("tool-status").textContent="  延伸完成";
      }
    }
    
    saveState();render2D();rebuild3D();updateStatus();
    trimMode = false;
    return true;
  }
  return false;
}

function lineIntersection(x1,y1,x2,y2,x3,y3,x4,y4){
  var d = (x1-x2)*(y3-y4) - (y1-y2)*(x3-x4);
  if(Math.abs(d)<0.001)return null;
  var t = ((x1-x3)*(y3-y4) - (y1-y3)*(x3-x4)) / d;
  var u = -((x1-x2)*(y1-y3) - (y1-y2)*(x1-x3)) / d;
  if(t>=-0.01 && t<=1.01 && u>=-0.01 && u<=1.01){
    return {x: x1 + t*(x2-x1), y: y1 + t*(y2-y1)};
  }
  return null;
}
"""

am = "// ===================== ANIMATION LOOP"
if am in html:
    html = html.replace(am, trim_code + am)
    c+=1; print("+ Trim/Extend commands")

# Integrate trim into pointerdown (before select handler)
old_select = "  // select\n  const hit=hitTest(wp.x,wp.y);"
new_select = "  if(trimMode&&doTrimOrExtend(wp)){return;}\n"+old_select
if old_select in html:
    html = html.replace(old_select, new_select)
    c+=1; print("+ Trim integration")

# Add trim/extend buttons to props panel
old_offset = 'onclick="doOffset()">偏移</button>'
if 'activateTrim()' not in html:
    html = html.replace(old_offset, 'onclick="doOffset()">偏移</button>\n      <button class="btn" style="padding:2px 6px;font-size:10px" onclick="activateTrim()">修剪</button>\n      <button class="btn" style="padding:2px 6px;font-size:10px" onclick="activateExtend()">延伸</button>')
    c+=1; print("+ Trim/Extend buttons")

# ==================== 2. CTB FILE EXPORT ====================
ctb_export = """
// ===================== CTB 文件导出 =====================
window.exportCTB = function(){
  var ctb = "!CTB_FILE\\n";
  ctb += "  CTB version 1.0\\n";
  ctb += "  Generated by CAD Interior Designer\\n\\n";
  var colors = {"1":"红","2":"黄","3":"绿","4":"青","5":"蓝","6":"品红","7":"白","8":"灰"};
  for(var k in CTB.color){
    var c = CTB.color[k];
    ctb += "color: "+k+"\\n";
    ctb += "  name: "+colors[k]+"\\n";
    ctb += "  weight: "+c.weight.toFixed(2)+"\\n";
    ctb += "  halftone: "+c.halftone+"\\n";
    ctb += "  linetype: solid\\n\\n";
  }
  var blob = new Blob([ctb], {type:"text/plain"});
  var a = document.createElement("a");
  a.download = "floorplan.ctb";
  a.href = URL.createObjectURL(blob);
  a.click();
  document.getElementById("tool-status").textContent="  CTB打印样式已导出";
};
"""

if am in html:
    html = html.replace(am, ctb_export + am)
    c+=1; print("+ CTB file export")

# Add CTB export button
old_ctb_btn = 'onclick="showCTB()"> CTB</button>'
if 'exportCTB()' not in html:
    html = html.replace(old_ctb_btn, 'onclick="showCTB()"> CTB</button>\n      <button class="btn" onclick="exportCTB()"> CTB导出</button>')
    c+=1; print("+ CTB export button")

# ==================== 3. TEMPLATE LIBRARY ====================
templates = """
// ===================== 户型模板库 =====================
var FLOORPLAN_TEMPLATES = {
  "两室一厅 80m2": {
    walls: [
      {id:1,x1:0,y1:0,x2:10000,y2:0,thick:240,type:"外墙"},
      {id:2,x1:10000,y1:0,x2:10000,y2:10000,thick:240,type:"外墙"},
      {id:3,x1:10000,y1:10000,x2:0,y2:10000,thick:240,type:"外墙"},
      {id:4,x1:0,y1:10000,x2:0,y2:0,thick:240,type:"外墙"},
      {id:5,x1:0,y1:4000,x2:4500,y2:4000,thick:150,type:"内墙"},
      {id:6,x1:5500,y1:4000,x2:10000,y2:4000,thick:150,type:"内墙"},
      {id:7,x1:4500,y1:0,x2:4500,y2:5000,thick:150,type:"内墙"},
      {id:8,x1:5500,y1:0,x2:5500,y2:5000,thick:150,type:"内墙"},
      {id:9,x1:6000,y1:4000,x2:6000,y2:5000,thick:150,type:"内墙"},
      {id:10,x1:7000,y1:4000,x2:7000,y2:5000,thick:150,type:"内墙"},
      {id:11,x1:6000,y1:5000,x2:6000,y2:10000,thick:150,type:"内墙"},
      {id:12,x1:0,y1:5000,x2:10000,y2:5000,thick:150,type:"内墙"},
    ],
    doors: [{wallId:5,pos:2000,width:900},{wallId:12,pos:3000,width:900},{wallId:8,pos:2000,width:800}],
    windows: [{wallId:2,pos:5000,width:1500},{wallId:3,pos:3000,width:1500}],
    rooms: [
      {name:"客厅",corners:[{x:0,y:5000},{x:6000,y:5000},{x:6000,y:10000},{x:0,y:10000}],color:"#667eea",area:30},
      {name:"餐厅",corners:[{x:6000,y:5000},{x:10000,y:5000},{x:10000,y:10000},{x:6000,y:10000}],color:"#764ba2",area:20},
      {name:"主卧",corners:[{x:0,y:0},{x:4500,y:0},{x:4500,y:4000},{x:0,y:4000}],color:"#f093fb",area:18},
      {name:"次卧",corners:[{x:5500,y:0},{x:10000,y:0},{x:10000,y:4000},{x:5500,y:4000}],color:"#4facfe",area:18},
      {name:"厨房",corners:[{x:7000,y:4000},{x:10000,y:4000},{x:10000,y:5000},{x:7000,y:5000}],color:"#43e97b",area:6},
      {name:"卫生间",corners:[{x:6000,y:4000},{x:7000,y:4000},{x:7000,y:5000},{x:6000,y:5000}],color:"#fa709a",area:5},
    ],
  },
  "三室一厅 120m2": {
    walls: [
      {id:1,x1:0,y1:0,x2:12000,y2:0,thick:240,type:"外墙"},
      {id:2,x1:12000,y1:0,x2:12000,y2:10000,thick:240,type:"外墙"},
      {id:3,x1:12000,y1:10000,x2:0,y2:10000,thick:240,type:"外墙"},
      {id:4,x1:0,y1:10000,x2:0,y2:0,thick:240,type:"外墙"},
      {id:5,x1:0,y1:3500,x2:5000,y2:3500,thick:150,type:"内墙"},
      {id:6,x1:7000,y1:3500,x2:12000,y2:3500,thick:150,type:"内墙"},
      {id:7,x1:5000,y1:0,x2:5000,y2:4500,thick:150,type:"内墙"},
      {id:8,x1:7000,y1:0,x2:7000,y2:4500,thick:150,type:"内墙"},
      {id:9,x1:0,y1:4500,x2:12000,y2:4500,thick:150,type:"内墙"},
      {id:10,x1:6000,y1:4500,x2:6000,y2:10000,thick:150,type:"内墙"},
      {id:11,x1:0,y1:7000,x2:6000,y2:7000,thick:150,type:"内墙"},
    ],
    doors: [{wallId:5,pos:2000,width:900},{wallId:7,pos:2000,width:900},{wallId:8,pos:2000,width:900},{wallId:9,pos:3000,width:900},{wallId:11,pos:2000,width:900}],
    windows: [{wallId:2,pos:6000,width:1800},{wallId:3,pos:3000,width:1500},{wallId:4,pos:2000,width:1500}],
    rooms: [
      {name:"客厅",corners:[{x:6000,y:4500},{x:12000,y:4500},{x:12000,y:10000},{x:6000,y:10000}],color:"#667eea",area:33},
      {name:"主卧",corners:[{x:0,y:0},{x:5000,y:0},{x:5000,y:3500},{x:0,y:3500}],color:"#f093fb",area:17.5},
      {name:"次卧1",corners:[{x:7000,y:0},{x:12000,y:0},{x:12000,y:3500},{x:7000,y:3500}],color:"#4facfe",area:17.5},
      {name:"次卧2",corners:[{x:5000,y:0},{x:7000,y:0},{x:7000,y:4500},{x:5000,y:4500}],color:"#a8a8a8",area:9},
      {name:"厨房",corners:[{x:0,y:4500},{x:6000,y:4500},{x:6000,y:7000},{x:0,y:7000}],color:"#43e97b",area:15},
      {name:"卫生间",corners:[{x:0,y:7000},{x:6000,y:7000},{x:6000,y:10000},{x:0,y:10000}],color:"#fa709a",area:18},
    ],
  },
};

window.loadTemplate = function(name){
  var t = FLOORPLAN_TEMPLATES[name];
  if(!t) return;
  walls.length=0; doors.length=0; windows.length=0; rooms.length=0; dims.length=0; furniture.length=0;
  t.walls.forEach(function(w){walls.push({id:nextId++,x1:w.x1,y1:w.y1,x2:w.x2,y2:w.y2,thick:w.thick,type:w.type})});
  t.doors.forEach(function(d){doors.push({id:nextId++,wallId:d.wallId,pos:d.pos,width:d.width})});
  t.windows.forEach(function(w){windows.push({id:nextId++,wallId:w.wallId,pos:w.pos,width:w.width})});
  t.rooms.forEach(function(r){rooms.push({id:nextId++,name:r.name,corners:r.corners,color:r.color,area:r.area})});
  saveState();render2D();rebuild3D();updateStatus();
  document.getElementById("tool-status").textContent="  已加载: "+name;
  zoomFit();
};

window.showTemplates = function(){
  var names = Object.keys(FLOORPLAN_TEMPLATES);
  var msg = "选择户型模板:\\n\\n";
  for(var i=0;i<names.length;i++){
    msg += (i+1)+". "+names[i]+"\\n";
  }
  var choice = prompt(msg, "1");
  if(choice){
    var idx = parseInt(choice)-1;
    if(idx>=0 && idx<names.length){
      if(confirm("加载 \\""+names[idx]+"\\" 将清空当前绘图")){
        loadTemplate(names[idx]);
      }
    }
  }
};
"""

if am in html:
    html = html.replace(am, templates + am)
    c+=1; print("+ Template library")

# Add template button
old_ctb_export = 'onclick="exportCTB()"> CTB导出</button>'
if 'showTemplates()' not in html:
    html = html.replace(old_ctb_export, 'onclick="exportCTB()"> CTB导出</button>\n      <button class="btn btn-p" onclick="showTemplates()"> 模板</button>')
    c+=1; print("+ Template button")

with open("E:/CAD自动化制图/interior_cad.html","w",encoding="utf-8") as f:
    f.write(html)
print(f"Done! {c} changes, {len(html)} bytes")
